2019-01-31 11:22:04,029 - CommonUtils.py[line:311] - ERROR: 删除日志成功
2019-01-31 11:22:07,375 - ProxyIPUtil.py[line:165] - INFO: 测试代理IP,切换代理IP:221.6.201.18:9999
